
local Target = {
    Travellingmerchant = {
        vector4(-119.66, -977.43, 304.25, 88.21),
        vector4(-1522.93, 1476.01, 111.45, 41.25),
        vector4(-3278.98, 973.38, 5.35, 101.53),
    },
}

local loc = Target.Travellingmerchant[math.random(1, #Target.Travellingmerchant)]

local stores = {
	travel = {
		tab_paper 	     	= 50,
		bakingsoda 	     	= 25,
		isosafrole 	     	= 25,
		mdp2p 		     	= 25,
		lysergic_acid    	= 25,
		diethylamide     	= 25,
		lockpick  	     	= 2,
		emptyvial 	     	= 2,
		needle 		   	 	= 2,
		cokeburner 	     	= 25,
		crackburner 	 	= 2,
		lsdburner	   	 	= 2,
		heroinburner     	= 2,
		mdlean 		     	= 50,
		weedgrinder 	 	= 25,
		mdbutter 	     	= 25,
		flour 		     	= 25,
		chocolate  	     	= 25,
		butane 		     	= 25,
		butanetorch 	   	= 2,
		dabrig 		   		= 2,
		mdwoods 		   	= 2,
		leancup 		   	= 25,
		xtcburner 	   		= 25,
	},
}

ps.registerCallback('md-drugs:server:GetMerchant', function(source)
	return {loc = loc, items = stores.travel}
end)



RegisterServerEvent("md-drugs:server:purchaseGoods", function(item)
	local src = source
	if not ps.checkDistance(src, loc, 10) then
		ps.notify(src, ps.lang('Catches.notIn'), "error")
		return
	end
	if not stores.travel[item] then
		ps.notify(src, ps.lang('Catches.invalidItem'), "error")
		return
	end
	if ps.removeMoney(src, 'cash', stores.travel[item]) then
		ps.addItem(src, item, 1)
	else
		ps.notify(src, ps.lang('Catches.notEnoughMoney'), "error")
	end
end)

local itemList = {

	coke 		 	 	 	     = true,
    coca_leaf 		 	 	 	 = true,
    bakingsoda 		 	 	     = true,
    loosecoke 			 		 = true,
    loosecokestagetwo 			 = true,
    loosecokestagethree 		 = true,
    cokebaggy                    = true,
    cokebaggystagetwo 			 = true,
    cokebaggystagethree 		 = true,
    cokestagetwo 		 	 	 = true,
    cokestagethree 		 	 	 = true,
    empty_weed_bag               = true,

    bakingsoda 		 	 	     = true,
    baggedcracked 		 	 	 = true,
    baggedcrackedstagetwo 		 = true,
    baggedcrackedstagethree 	 = true,
    crackrock 		 	 	 	 = true,
    crackrockstagetwo 		 	 = true,
    crackrockstagethree 		 = true,
    empty_weed_bag               = true,

    bakingsoda 		 	 	     = true,
    poppyresin 		 	 	     = true,
    heroin 		 	 	 	     = true,
    heroinstagetwo 		 	 	 = true,
    heroinstagethree 		 	 = true,
    heroincut 		 	 	 	 = true,
    heroincutstagetwo 		 	 = true,
    heroincutstagethree 		 = true,
    heroinlabkit 		 	 	 = true,
    heroinvial 		 	 	 	 = true,
    heroinvialstagetwo 		 	 = true,
    heroinvialstagethree 		 = true,
    heroin_ready 		 	 	 = true,
    heroin_readystagetwo 		 = true,
    heroin_readystagethree 		 = true,
    emptyvial 				     = true,
    needle 		 				 = true,

    sprunk 				    	 = true,
    leancup 				     = true,
    cupoflean 				     = true,
    cupofdextro 				 = true,
    mdlean 				         = true,
    mdreddextro 				 = true,

    lysergic_acid 			 	 = true,
    diethylamide 			 	 = true,
    lsd_one_vial 			 	 = true,
    lsd_vial_two 			 	 = true,
    lsd_vial_three 			 	 = true,
    lsd_vial_four 			 	 = true,
    lsd_vial_five 			 	 = true,
    lsd_vial_six 			 	 = true,
    tab_paper 			 		 = true,
    smileyfacesheet 			 = true,
    wildcherrysheet 			 = true,
    yinyangsheet 			     = true,
    pineapplesheet 			 	 = true,
    bart_tabs 			 		 = true,
    bartsheet 			 		 = true,
    gratefuldeadsheet 			 = true,
    smiley_tabs 			     = true,
    wildcherry_tabs 			 = true,
    yinyang_tabs 			     = true,
    pineapple_tabs 			     = true,
    gratefuldead_tabs 			 = true,
    lsdlabkit 			 		 = true,

    cactusbulb 				     = true,
    driedmescaline 				 = true,

    ephedrine 				     = true,
    acetone 				     = true,
    methbags 				     = true,
    empty_weed_bag               = true,

    prescription_pad 		     = true,
    vicodin_prescription 		 = true,
    adderal_prescription 		 = true,
    morphine_prescription 		 = true,
    xanax_prescription 		 	 = true,
    adderal 			    	 = true,
    vicodin 			    	 = true,
    morphine 			    	 = true,
    xanax 			     		 = true,
    adderalbottle 			     = true,
    vicodinbottle 			     = true,
    morphinebottle 			     = true,
    xanaxbottle 			     = true,

    wetcannabis 				 = true,
    drycannabis 				 = true,
    weedgrinder 				 = true,
    mdbutter 				     = true,
    cannabutter 				 = true,
    specialbrownie 				 = true,
    specialcookie 				 = true,
    specialmuffin 				 = true,
    specialchocolate 			 = true,
    grindedweed 				 = true,
    flour 				         = true,
    chocolate 				     = true,
    blunt 				    	 = true,
    butane 				    	 = true,
    butanetorch 				 = true,
    dabrig 				     	 = true,
    mdwoods 				     = true,
    ciggie 				    	 = true,
    tobacco 				     = true,
    shatter 				     = true,
    bluntwrap 				     = true,
    leanbluntwrap 				 = true,
    dextroblunt 				 = true,
    dextrobluntwrap 			 = true,
    leanblunts 				     = true,
    dextroblunts 				 = true,
    chewyblunt 				     = true,

    cokeburner 				     = true,
    crackburner 				 = true,
    heroinburner 				 = true,
    lsdburner 				     = true,
    xtcburner 				     = true,

    isosafrole 			 		 = true,
    mdp2p 			 			 = true,
    raw_xtc 				     = true,
    singlepress 				 = true,
    dualpress 				 	 = true,
    triplepress 				 = true,
    quadpress 					 = true,
    white_xtc 				     = true,
    white_xtc2 				     = true,
    white_xtc3 				     = true,
    white_xtc4 				     = true,
    red_xtc 				     = true,
    red_xtc2 				     = true,
    red_xtc3 				     = true,
    red_xtc4 				     = true,
    orange_xtc 				     = true,
    orange_xtc2 				 = true,
    orange_xtc3 				 = true,
    orange_xtc4 				 = true,
    blue_xtc 				     = true,
    blue_xtc2 				     = true,
    blue_xtc3 				     = true,
    blue_xtc4 				     = true,
    white_playboys 				 = true,
    white_playboys2 			 = true,
    white_playboys3 			 = true,
    white_playboys4 			 = true,
    blue_playboys 				 = true,
    blue_playboys2 				 = true,
    blue_playboys3 				 = true,
    blue_playboys4 				 = true,
    red_playboys 				 = true,
    red_playboys2 				 = true,
    red_playboys3 				 = true,
    red_playboys4 				 = true,
    orange_playboys 			 = true,
    orange_playboys2 			 = true,
    orange_playboys3 			 = true,
    orange_playboys4 			 = true,
    white_aliens 				 = true,
    white_aliens2 				 = true,
    white_aliens3 				 = true,
    white_aliens4 				 = true,
    blue_aliens 				 = true,
    blue_aliens2 				 = true,
    blue_aliens3 				 = true,
    blue_aliens4 				 = true,
    red_aliens 					 = true,
    red_aliens2 				 = true,
    red_aliens3 				 = true,
    red_aliens4 				 = true,
    orange_aliens 				 = true,
    orange_aliens2 				 = true,
    orange_aliens3 				 = true,
    orange_aliens4 				 = true,
    white_pl 					 = true,
    white_pl2 					 = true,
    white_pl3 					 = true,
    white_pl4 					 = true,
    blue_pl 					 = true,
    blue_pl2 					 = true,
    blue_pl3 					 = true,
    blue_pl4 					 = true,
    red_pl 						 = true,
    red_pl2 					 = true,
    red_pl3 					 = true,
    red_pl4 					 = true,
    orange_pl 					 = true,
    orange_pl2 					 = true,
    orange_pl3 					 = true,
    orange_pl4 					 = true,
    white_trolls 				 = true,
    white_trolls2 				 = true,
    white_trolls3 				 = true,
    white_trolls4 				 = true,
    blue_trolls 				 = true,
    blue_trolls2 				 = true,
    blue_trolls3 				 = true,
    blue_trolls4 				 = true,
    red_trolls 					 = true,
    red_trolls2 				 = true,
    red_trolls3 				 = true,
    red_trolls4 				 = true,
    orange_trolls 				 = true,
    orange_trolls2 				 = true,
    orange_trolls3 				 = true,
    orange_trolls4 				 = true,
    white_cats 					 = true,
    white_cats2 				 = true,
    white_cats3 				 = true,
    white_cats4 				 = true,
    blue_cats 					 = true,
    blue_cats2 					 = true,
    blue_cats3 					 = true,
    blue_cats4 					 = true,
    red_cats 					 = true,
    red_cats2 					 = true,
    red_cats3 					 = true,
    red_cats4 					 = true,
    orange_cats 				 = true,
    orange_cats2 				 = true,
    orange_cats3 				 = true,
    orange_cats4 				 = true,
}

RegisterCommand('testImages', function(source)
	local src = source
	for k, v in pairs(itemList) do
		ps.addItem(src, k, 1)
	end
end)