Config.Cornerselling = {
    noSellZones = {
        {loc = vector3(445.11, -991.3, 30.69), width = 10.0, length = 10.0, height = 10.0, rot = 180.0},
    },
    CornerSellLevel = {
       {price = 0.5, minrep = 0,    maxrep = 240,  label = 'Rookie'},
       {price = 1.0, minrep = 240,  maxrep = 600,  label = 'Corner Boy'},
       {price = 1.1, minrep = 600,  maxrep = 1200, label = 'Corner Man'},
       {price = 1.2, minrep = 1200, maxrep = 1800, label = 'Dope Peddler'},
       {price = 1.3, minrep = 1800, maxrep = 2400, label = 'Drug Supplier'},
       {price = 1.5, minrep = 2400, maxrep = 4800, label = 'Drug Pusher'},
       {price = 1.75, minrep = 4800, maxrep = 99999999999999, label = 'Drug Lord'},
    },
    Drugs = {
        ["weed_white-widow"] =          {rep = 1,min = 15, max = 24 },
        ["weed_og-kush"] =              {rep = 1,min = 15, max = 28 },
        ["weed_skunk"] =                {rep = 1,min = 15, max = 31 },
        ["weed_amnesia"] =              {rep = 1,min = 18, max = 34 },
        ["weed_purple-haze"] =          {rep = 1,min = 18, max = 37},
        ["weed_ak47"] =                 {rep = 1,min = 18, max = 40},
        ["crack_baggy"] =               {rep = 1,min = 18, max = 34},
        ["cokebaggy"] =                 {rep = 1,min = 18, max = 37},
        ["cokebaggystagetwo"] =         {rep = 1,min = 18, max = 40},
        ["cokebaggystagethree"] =       {rep = 1,min = 18, max = 40},
        ["heroin_ready"] =              {rep = 1,min = 18, max = 40},
        ["heroin_readystagetwo"] =      {rep = 1,min = 18, max = 40},
        ["heroin_readystagethree"] =    {rep = 1,min = 18, max = 40},
        ["baggedcracked"] =             {rep = 1,min = 18, max = 40},
        ["baggedcrackedstagetwo"] =     {rep = 1,min = 18, max = 40},
        ["baggedcrackedstagethree"] =   {rep = 1,min = 18, max = 40},
        ["white_playboys"] =            {rep = 1,min = 18, max = 40},
        ["white_playboys2"] =           {rep = 1,min = 18, max = 40},
        ["white_playboys3"] =           {rep = 1,min = 18, max = 40},
        ["white_playboys4"] =           {rep = 1,min = 18, max = 40},
        ["blue_playboys"] =             {rep = 1,min = 18, max = 40},
        ["blue_playboys2"] =            {rep = 1,min = 18, max = 40},
        ["blue_playboys3"] =            {rep = 1,min = 18, max = 40},
        ["blue_playboys4"] =            {rep = 1,min = 18, max = 40},
        ["red_playboys"] =              {rep = 1,min = 18, max = 40},
        ["red_playboys2"] =             {rep = 1,min = 18, max = 40},
        ["red_playboys3"] =             {rep = 1,min = 18, max = 40},
        ["red_playboys4"] =             {rep = 1,min = 18, max = 40},
        ["orange_playboys"] =           {rep = 1,min = 18, max = 40},
        ["orange_playboys2"] =          {rep = 1,min = 18, max = 40},
        ["orange_playboys3"] =          {rep = 1,min = 18, max = 40},
        ["orange_playboys4"] =          {rep = 1,min = 18, max = 40},
        ["white_aliens"] =              {rep = 1,min = 18, max = 40},
        ["white_aliens2"] =             {rep = 1,min = 18, max = 40},
        ["white_aliens3"] =             {rep = 1,min = 18, max = 40},
        ["white_aliens4"] =             {rep = 1,min = 18, max = 40},
        ["blue_aliens"] =               {rep = 1,min = 18, max = 40},
        ["blue_aliens2"] =              {rep = 1,min = 18, max = 40},
        ["blue_aliens3"] =              {rep = 1,min = 18, max = 40},
        ["blue_aliens4"] =              {rep = 1,min = 18, max = 40},
        ["red_aliens"] =                {rep = 1,min = 18, max = 40},
        ["red_aliens2"] =               {rep = 1,min = 18, max = 40},
        ["red_aliens3"] =               {rep = 1,min = 18, max = 40},
        ["red_aliens4"] =               {rep = 1,min = 18, max = 40},
        ["orange_aliens"] =             {rep = 1,min = 18, max = 40},
        ["orange_aliens2"] =            {rep = 1,min = 18, max = 40},
        ["orange_aliens3"] =            {rep = 1,min = 18, max = 40},
        ["orange_aliens4"] =            {rep = 1,min = 18, max = 40},
        ["white_pl"] =                  {rep = 1,min = 18, max = 40},
        ["white_pl2"] =                 {rep = 1,min = 18, max = 40},
        ["white_pl3"] =                 {rep = 1,min = 18, max = 40},
        ["white_pl4"] =                 {rep = 1,min = 18, max = 40},
        ["blue_pl"] =                   {rep = 1,min = 18, max = 40},
        ["blue_pl2"] =                  {rep = 1,min = 18, max = 40},
        ["blue_pl3"] =                  {rep = 1,min = 18, max = 40},
        ["blue_pl4"] =                  {rep = 1,min = 18, max = 40},
        ["red_pl"] =                    {rep = 1,min = 18, max = 40},
        ["red_pl2"] =                   {rep = 1,min = 18, max = 40},
        ["red_pl3"] =                   {rep = 1,min = 18, max = 40},
        ["red_pl4"] =                   {rep = 1,min = 18, max = 40},
        ["orange_pl"] =                 {rep = 1,min = 18, max = 40},
        ["orange_pl2"] =                {rep = 1,min = 18, max = 40},
        ["orange_pl3"] =                {rep = 1,min = 18, max = 40},
        ["orange_pl4"] =                {rep = 1,min = 18, max = 40},
        ["white_trolls"] =              {rep = 1,min = 18, max = 40},
        ["white_trolls2"] =             {rep = 1,min = 18, max = 40},
        ["white_trolls3"] =             {rep = 1,min = 18, max = 40},
        ["white_trolls4"] =             {rep = 1,min = 18, max = 40},
        ["blue_trolls"] =               {rep = 1,min = 18, max = 40},
        ["blue_trolls2"] =              {rep = 1,min = 18, max = 40},
        ["blue_trolls3"] =              {rep = 1,min = 18, max = 40},
        ["blue_trolls4"] =              {rep = 1,min = 18, max = 40},
        ["red_trolls"] =                {rep = 1,min = 18, max = 40},
        ["red_trolls2"] =               {rep = 1,min = 18, max = 40},
        ["red_trolls3"] =               {rep = 1,min = 18, max = 40},
        ["red_trolls4"] =               {rep = 1,min = 18, max = 40},
        ["orange_trolls"] =             {rep = 1,min = 18, max = 40},
        ["orange_trolls2"] =            {rep = 1,min = 18, max = 40},
        ["orange_trolls3"] =            {rep = 1,min = 18, max = 40},
        ["orange_trolls4"] =            {rep = 1,min = 18, max = 40},
        ["white_cats"] =                {rep = 1,min = 18, max = 40},
        ["white_cats2"] =               {rep = 1,min = 18, max = 40},
        ["white_cats3"] =               {rep = 1,min = 18, max = 40},
        ["white_cats4"] =               {rep = 1,min = 18, max = 40},
        ["blue_cats"] =                 {rep = 1,min = 18, max = 40},
        ["blue_cats2"] =                {rep = 1,min = 18, max = 40},
        ["blue_cats3"] =                {rep = 1,min = 18, max = 40},
        ["blue_cats4"] =                {rep = 1,min = 18, max = 40},
        ["red_cats"] =                  {rep = 1,min = 18, max = 40},
        ["red_cats2"] =                 {rep = 1,min = 18, max = 40},
        ["red_cats3"] =                 {rep = 1,min = 18, max = 40},
        ["red_cats4"] =                 {rep = 1,min = 18, max = 40},
        ["orange_cats"] =               {rep = 1,min = 18, max = 40},
        ["orange_cats2"] =              {rep = 1,min = 18, max = 40},
        ["orange_cats3"] =              {rep = 1,min = 18, max = 40},
        ["orange_cats4"] =              {rep = 1,min = 18, max = 40},	
        ["blunts"] =                    {rep = 1,min = 18, max = 40},
        ["leanblunts"] =                {rep = 1,min = 18, max = 40},
        ["dextroblunts"] =              {rep = 1,min = 18, max = 40},
        ["chewyblunt"] =                {rep = 1,min = 18, max = 40},
        ["blunt"] =                     {rep = 1,min = 18, max = 40},
        ["specialchocolate"] =          {rep = 1,min = 18, max = 40},
        ["specialbrownie"] =            {rep = 1,min = 18, max = 40},
        ["specialcookie"] =             {rep = 1,min = 18, max = 40},
        ["specialmuffin"] =             {rep = 1,min = 18, max = 40},
        ["shatter"] =                   {rep = 1,min = 18, max = 40},
        ["ciggie"] =                    {rep = 1,min = 18, max = 40},
        ["methbags"] =                  {rep = 1,min = 18, max = 40},
        ["driedmescaline"] =            {rep = 1,min = 18, max = 40},
        ["shrooms"] =                   {rep = 1,min = 18, max = 40},
        ["gratefuldead_tabs"] =         {rep = 1,min = 18, max = 40},
        ["bart_tabs"] =                 {rep = 1,min = 18, max = 40},
        ["pineapple_tabs"] =            {rep = 1,min = 18, max = 40},
        ["yinyang_tabs"] =              {rep = 1,min = 18, max = 40},
        ["wildcherry_tabs"] =           {rep = 1,min = 18, max = 40},
        ["smiley_tabs"] =               {rep = 1,min = 18, max = 40},
        ["cupoflean"] =                 {rep = 1,min = 18, max = 40},
        ["cupofdextro"] =               {rep = 1,min = 18, max = 40},
    },
    config = {
        MarkedBills = false, -- if you want to use qb markedbills for selling set to true, if you want to use a custom item or cash set to false
        CustomItem = '', -- If you want to use a custom item for selling, put the item name here, if not leave it blank '' 
        --- if MarkedBills is false and CustomItem is blank it will pay cash
        policeRequired = 0, -- if you want cops to be required to sell set this to a number above 0
        robChance = 20, -- Chance To Be Robbed 1 = 1%
    }
}